### ISSUE TITLE
Simulator's status keys differ from real ACU's

### ISSUE THREAD

**Issue by BrianJKoopman** [simonsobs/soaculib#24]
The simulator has diverged from the real ACU's status keys. See https://github.com/simonsobs/sorunlib/issues/72 for an example of this. These should be updated in the simulator.

**Comment by mhasself** [comment]
It looks like the simulator keeps 3 keys in sync:

```
    def update_positions(self, new_az=None, new_el=None, new_bs=None):
        if new_az is not None:
            self.data['Azimuth current position'] = new_az
            self.data['Raw Azimuth'] = new_az
            self.data['Corrected Azimuth'] = new_az
        if new_el is not None:
            self.data['Elevation current position'] = new_el
            self.data['Raw Elevation'] = new_el
            self.data['Corrected Elevation'] = new_el
        if new_bs is not None:
            self.data['Boresight current position'] = new_bs
            self.data['Raw Boresight'] = new_bs
            self.data['Corrected Boresight'] = new_bs
```

I think the Raw / Corrected values are kept here so that the udp_server can copy them into the UDP frames.  I think the easiest thing for now is to just pretend they aren't there, and use "{axis} current position", as one would for the real ACU.
